# Generated by Django 6.0.4 on 2026-04-27 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_user_managers_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistprofile',
            options={'verbose_name': 'Профиль специалиста', 'verbose_name_plural': 'Профиль специалистов'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['workdays', 'from_hour'], 'verbose_name': 'Рабочие дни', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CL'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_bookings', to='booking.specialistprofile'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
